### ISSUE TITLE
Unresponsive host

### ISSUE THREAD

**Issue by stablestud** [sedrubal/adaway-linux#19]
[Malwaredomainlist.com](https://www.malwaredomainlist.com) seems to be often unreachable, probably due to DDOS attacks.
Therefore the setup takes significantly longer and exits with  `exit 1` when used with `wget`. This will terminate the script even though the other hosts were reachable. Applying the adblock will fail. 

This is fixed in [stderr](https://github.com/sedrubal/adaway-linux/pull/18) #18 with removing `set -e`, however I wouldn't recommend to use **malwaredomainlist.com** as its unreliable.

So I suggest we remove it - or atleast comment it out by default.

**Comment by sedrubal** [comment]
That's a good idea.

But I wouldn't remove `set -e` but add something like `wget ... || (>&2 echo "Download failed")`
