### ISSUE TITLE
cronjob handling

### ISSUE THREAD

**Issue by Targunitoth** [sedrubal/adaway-linux#21]
Hello,
why are you writing the cronjob into sudos crontab,
can't you just handle the cronjobs in a new file in `/etc/cron.d`?
(e. g. https://unix.stackexchange.com/a/296351)

**Comment by sedrubal** [comment]
Yes, that would be much saner. I'm open for pull requests.

**Comment by Targunitoth** [comment]
Here is my pull request.
I also suggest to set the default value for updating to daily instead of weekly, for a better user experience.
